### PR TITLE
fix: GoogleGemini generation_config param

### LINKED ISSUE #648: Google Gemini LLM generation config problem
The following line in Google Gemini LLM seems to be wrong.
If the `temperature` is defined, the whole `generation_config` object gets replaced thus ignoring any pre defined parameters there!

https://github.com/patterns-ai-core/langchainrb/blob/0efc39269e5c2c123886fa34e10b28c682ada948/lib/langchain/llm/google_gemini.rb#L45

### PR DESCRIPTION
**Pull request by mazenkhalil**
Fixes #648

### CODE REVIEW

**Comment by andreibondarev** [comment]
@mazenkhalil Do you think you could add a quick spec?

**Comment by mazenkhalil** [comment]
> @mazenkhalil Do you think you could add a quick spec?

I have synced the whole implementation with GeminiAPI & and I have added the tests

File: lib/langchain/llm/google_gemini.rb [hunk 1]
```diff
@@ -1,5 +1,8 @@
 # frozen_string_literal: true
 
+require "active_support/core_ext/hash/keys"
+require "active_support/core_ext/string/inflections"
```
Comment (andreibondarev) [inline lib/langchain/llm/google_gemini.rb:4]: Do we need to use `active_support`? I specifically [removed it](https://github.com/patterns-ai-core/langchainrb/pull/639) to reduce the number of dependencies.

Comment (mazenkhalil) [reply lib/langchain/llm/google_gemini.rb:4]: Two utilities have been used. I am not much familiar with Ruby. if there's another way to implement that, I'm open to suggestions

File: lib/langchain/llm/google_gemini.rb [hunk 2]
```diff
@@ -42,13 +47,25 @@ def chat(params = {})
...
+      parameters.delete(:response_format)
+      parameters[:generation_config][:stop_sequences] ||= parameters[:stop] if parameters[:stop]
+      parameters.delete(:stop)
 
       uri = URI("https://generativelanguage.googleapis.com/v1beta/models/#{parameters[:model]}:generateContent?key=#{api_key}")
 
       request = Net::HTTP::Post.new(uri)
       request.content_type = "application/json"
-      request.body = parameters.to_json
+      request.body = parameters.deep_transform_keys { |key| key.to_s.camelize(:lower).to_sym }.to_json
```
Comment (andreibondarev) [inline lib/langchain/llm/google_gemini.rb:68]: Do we actually need to transform the keys here? Does it not work otherwise?

File: lib/langchain/llm/google_gemini.rb (hunk 1 above)
Comment (mazenkhalil) [reply lib/langchain/llm/google_gemini.rb]: I've created internal utils class

File: lib/langchain/llm/google_gemini.rb (hunk 2 above)
Comment (mazenkhalil) [reply lib/langchain/llm/google_gemini.rb]: It's important to note that merely having a working API implementation doesn't guarantee its stability over time. The best approach is to strictly adhere to the API specifications. Failure to do so may result in the API discontinuing support unexpectedly.

**Comment by mazenkhalil** [comment]
@andreibondarev Is there anything I can do to speed up the review process here?

File: lib/langchain/llm/google_gemini.rb [hunk 3]
```diff
@@ -42,13 +44,25 @@ def chat(params = {})
       raise ArgumentError.new("messages argument is required") if Array(params[:messages]).empty?
 
       parameters = chat_parameters.to_params(params)
-      parameters[:generation_config] = {temperature: parameters.delete(:temperature)} if parameters[:temperature]
+      parameters[:generation_config] ||= {}
+      parameters[:generation_config][:temperature] ||= parameters[:temperature] if parameters[:temperature]
+      parameters.delete(:temperature)
```
Comment (andreibondarev) [inline lib/langchain/llm/google_gemini.rb:49]: Why not change:
```ruby
parameters[:generation_config][:temperature] ||= parameters[:temperature] if parameters[:temperature]
parameters.delete(:temperature)
```
to
```ruby
parameters[:generation_config][:temperature] ||= parameters.delete(:temperature) if parameters[:temperature]
```
everywhere?

File: lib/langchain/utils/hash_transformer.rb [hunk 4]
```diff
@@ -0,0 +1,25 @@
+module Langchain
+  module Utils
+    class HashTransformer
```
Comment (andreibondarev) [inline lib/langchain/utils/hash_transformer.rb:3]: I'm wondering if we should've just yanked out the code out of the `activesupport` lib? This is fine, but I was wondering if it could be more elegant.

**Comment by andreibondarev** [comment]
> @andreibondarev Is there anything I can do to speed up the review process here?

A few comments, otherwise -- let's ship it!

File: lib/langchain/llm/google_gemini.rb (hunk 3 above)
Comment (mazenkhalil) [reply lib/langchain/llm/google_gemini.rb:49]: Because we always need to delete the parameter even if it is already defined in the generation_config. Otherwise actual payload will have additional unneeded parameters. This case already covered in the specs.

File: lib/langchain/utils/hash_transformer.rb (hunk 4 above)
Comment (mazenkhalil) [reply lib/langchain/utils/hash_transformer.rb:3]: The code here is 100% genuine, not copied from ActiveSupport in any way. In fact It is GPT generated.

**Comment by andreibondarev** [comment]
@mazenkhalil Thank you! Merged.
